### ISSUE TITLE
Ability to search for multiple words using "+"

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/banidb-api#89] opened 2019-09-25 05:15 UTC
gur + kirpa as an example

**Comment by ManjotS** [comment] 2019-12-03 20:02
this is a duplicate of #1

**Closed by ManjotS** 2019-12-03 20:02 UTC

**Comment by tarunsingh5** [comment] 2019-12-03 20:22
lets make this a priority given the IM request

**Comment by ManjotS** [comment] 2019-12-03 20:39
This is on Raj's plate
